<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\Behaviors\" />
    <Folder Include="Common\Exceptions\" />
    <Folder Include="Features\Documents\" />
    <Folder Include="Features\Users\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Mapster" Version="10.0.11" />
    <PackageReference Include="Mapster.DependencyInjection" Version="10.0.11" />
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrganizationAssetManagement.Domain\OrganizationAssetManagement.Domain.csproj" />
  </ItemGroup>

</Project>
